services:
  wordwebdb_api:
    build: ./api
    container_name: wordwebdb_api
    ports:
      - "5001:5001"
    depends_on:
      - postgres

  treelex:
    build: .
    container_name: treelex
    ports:
      - "5002:5002"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: